print("Tuple operations")
tuple1 = (4,40,50,45,78,89,40,60,40,"raja", "Ram",True)
print(tuple1.count(40))
print(tuple1.index("Ram"))
print("Set operations")
set1 = {1,5,70,"Ranjeet", False}
set1.add(111)
print(set1)
s2 = set1.copy()
print(s2)
x = set1.pop()
print(x)
print(set1)
print(set1.discard(5))
print(set1)
print(set1.remove(70))
print(set1)
set1.clear()
print(set1)
print("Dictionary operations")
dict1 = {"1":100, "ram": 200, "3": "seeta", "name": "Raja", "salary" : 15000}
print(dict1)
print("is dictionary:", isinstance(dict1, dict))
print("issubclass:", issubclass(dict, object))
#lowest = min(dict1, key=dict1.get)
print("Lowest stock item:", dict1.get)
print(dict1.keys())
print(dict1.values())
print(dict1.get("1"))
print(dict1.items())
print(dict1.popitem())
dict1.update(age=80)
dict1.update({"marks": 90})
print(dict1)
dict1.clear()
print(dict1)
#print(dict1.fromkeys())



