#Question: Perform basic operations on list, tuple, set, dictionary and string
list1 = [4,40,50,45,78,89,40,"raja", "Ram", None]
list1.append(90)
print(list1)
print(list1.count(40))
print(list1.index(40))
list1.insert(1,60)
print(list1)
x = list1.pop()
print(x)
y = list1.pop(9)
print(y)
print("remove:", list1.remove(4))
print(list1)
print(list1.remove(40))
print(list1)
list1.reverse()
print(list1)
#list1.sort()  -----> '<' not supported between instances of 'str' and 'NoneType'
#print(list1)
list2 = [3,90,72,45,83,6,50]
list2.sort()
print(list2)
l1 = sorted(list2)
print(l1)
list3 = ["Ram","Raja","Ranjeet","rani","Ravi","Raju","Raj"]
l4 = sorted(list3)
print(l4)
list1.extend([6,900,"tiger"])
print(list1,"\n")
l2 = list1.copy()
list1.append(1000)
print(list1)
l2.append(2000)
print(l2)
list1.clear()
print(list1)
print("Tuple operations")
tuple1 = (4,40,50,45,78,89,40,60,40,"raja", "Ram",True)
print(tuple1.count(40))
print(tuple1.index("Ram"))
print("Set operations")
set1 = {1,5,70,"Ranjeet", False}
set1.add(111)
print(set1)
s2 = set1.copy()
print(s2)
x = set1.pop()
print(x)
print(set1)
print(set1.discard(5))
print(set1)
print(set1.remove(70))
print(set1)
set1.clear()
print(set1)
print("Dictionary operations")
dict1 = {"1":100, "ram": 200, "3": "seeta", "name": "Raja", "salary" : 15000}
print(dict1)
print("is dictionary:", isinstance(dict1, dict))
print("issubclass:", issubclass(dict, object))
#lowest = min(dict1, key=dict1.get)
print("Lowest stock item:", dict1.get)
print(dict1.keys())
print(dict1.values())
print(dict1.get("1"))
print(dict1.items())
print(dict1.popitem())
dict1.update(age=80)
dict1.update({"marks": 90})
print(dict1)
dict1.clear()
print(dict1)
#print(dict1.fromkeys())



