print("String operations")
str1 = "automation Testing very good"
print("-----------------------------")
print(str1.capitalize())
print(str1.casefold())
#print(str1.center(" "))
print("count",str1.count("u",6,19))
print("find",str1.find("z",7,15))
print(str1.index("u"))
print(str1.index("u", 0, 10))
print("split:", str1.split(" "))
print("strip:", str1.strip())
print("isdigit:", str1.isdigit())
print("isalnum:", str1.isalnum())
print("isdecimal:", str1.isdecimal())
print("isnumeric:", str1.isnumeric())
print("istitle:", str1.istitle())
print("rfind:", str1.rfind("l"))
print("rindex:", str1.rindex("g"))
print("replace:", str1.replace("Testing", "Development"))
print("swapcase:", str1.swapcase())
print("title:", str1.title())   
print("upper:", str1.upper())
print("lower:", str1.lower())
print("startswith:", str1.startswith("Auto"))
print("endswith:", str1.endswith("Testing"))
print("join:", "-".join(str1))
print("len:", len(str1))
print("max:", max(str1))
print("min:", min(str1))
print("sorted:", sorted(str1))
print("reversed:", list(reversed(str1)))
print("enumerate:", list(enumerate(str1)))
print("format:", "Welcome to {}".format(str1))
print("f-string:", f"Welcome to {str1}")
print("zfill:", str1.zfill(40))
print("center:", str1.center(30, "*"))
print("lstrip:", str1.lstrip("Au"))
print("rstrip:", str1.rstrip("good"))
print("partition:", str1.partition("Testing"))
print("rpartition:", str1.rpartition("Testing"))
print("count:", str1.count("t", 0, 19))
print("find:", str1.find("t", 0, 19))
print("index:", str1.index("t", 0, 19))
print("rfind:", str1.rfind("t", 0, 19))
print("rindex:", str1.rindex("t", 1, 10))  
print("startswith:", str1.startswith("Auto", 0, 4))
print("endswith:", str1.endswith("Testing", 11, 19))
