print("Set operations")
set1 = {1,5,70,"Ranjeet", False}
set1.add(111)
print(set1)
s2 = set1.copy()
print(s2)
x = set1.pop()
print(x)
print(set1)
print(set1.discard(5))
print(set1)
print(set1.remove(70))
print(set1)
set1.clear()
print(set1)