list1 = [4,40,50,45,78,89,40,"raja", "Ram", None]
list1.append(90)
print(list1)
print(list1.count(40))
print(list1.index(40))
list1.insert(1,60)
print(list1)
x = list1.pop()
print(x)
y = list1.pop(9)
print(y)
print(list1.remove(4))
print(list1)
print(list1.remove(40))
print(list1)
list1.reverse()
print(list1)
#list1.sort()  -----> '<' not supported between instances of 'str' and 'NoneType'
#print(list1)
list2 = [3,90,72,45,83,6,50]
list2.sort()
print(list2)
l1 = sorted(list2)
print(l1)
list3 = ["Ram","Raja","Ranjeet","rani","Ravi","Raju","Raj"]
l4 = sorted(list3)
print(l4)
list1.extend([6,900,"tiger"])
print(list1,"\n")
l2 = list1.copy()
list1.append(1000)
print(list1)
l2.append(2000)
print(l2)
list1.clear()
print(list1)
print("Tuple operations")
tuple1 = (4,40,50,45,78,89,40,60,40,"raja", "Ram",True)
print(tuple1.count(40))
print(tuple1.index("Ram"))
print("Set operations")
set1 = {1,5,70,"Ranjeet", False}
set1.add(111)
print(set1)
s2 = set1.copy()
print(s2)
x = set1.pop()
print(x)
print(set1)
print(set1.discard(5))
print(set1)
print(set1.remove(70))
print(set1)
set1.clear()
print(set1)
print("Dictionary operations")
dict1 = {"1":100, "ram": 200, "3": "seeta", "name": "Raja", "salary" : 15000}
print(dict1)
print(dict1.keys())
print(dict1.values())
print(dict1.get("1"))
print(dict1.items())
print(dict1.popitem())
dict1.update(age=80)
print(dict1)
dict1.clear()
print(dict1)
#print(dict1.fromkeys())
print("String operations")
str1 = "Automation Testing"

print(str1.capitalize())
print(str1.casefold())
#print(str1.center(" "))
print(str1.count("u",6,19))
print(str1.find("o",7,15))
print(str1.index("u", 0, 10))
print("split:", str1.split(" "))
print("strip:", str1.strip())
print("isdigit:", str1.isdigit())
print("isalnum:", str1.isalnum())
print("isdecimal:", str1.isdecimal())
print("isnumeric:", str1.isnumeric())
print("istitle:", str1.istitle())
print("rfind:", str1.rfind("l"))
print("rindex:", str1.rindex("g"))
print("replace:", str1.replace("Testing", "Development"))
print("swapcase:", str1.swapcase())
print("title:", str1.title())   
print("upper:", str1.upper())
print("lower:", str1.lower())
print("startswith:", str1.startswith("Auto"))
print("endswith:", str1.endswith("Testing"))
print("join:", "-".join(str1))
print("len:", len(str1))
print("max:", max(str1))
print("min:", min(str1))
print("sorted:", sorted(str1))
print("reversed:", list(reversed(str1)))
print("enumerate:", list(enumerate(str1)))
print("format:", "Welcome to {}".format(str1))
print("f-string:", f"Welcome to {str1}")
print("zfill:", str1.zfill(25))
print("center:", str1.center(30, "*"))
print("lstrip:", str1.lstrip("A"))
print("rstrip:", str1.rstrip("g"))
print("partition:", str1.partition("Testing"))
print("rpartition:", str1.rpartition("Testing"))
print("count:", str1.count("t", 0, 19))
print("find:", str1.find("t", 0, 19))
print("index:", str1.index("t", 0, 19))
print("rfind:", str1.rfind("t", 0, 19))
print("rindex:", str1.rindex("t", 1, 10))  
print("startswith:", str1.startswith("Auto", 0, 4))
print("endswith:", str1.endswith("Testing", 11, 19))



